/**
 * Deliberately permissive UUID shape (8-4-4-4-12 hex), not RFC 4122
 * version/variant-strict. userId here is an opaque identifier owned and
 * generated by servora-auth — this service only needs to confirm the shape
 * is sane, not enforce a specific UUID version.
 */
export const UUID_PATTERN = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/;
